steps:
  # 1. Build la imatge Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA
      - .

  # 2. Push a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA

  # 3. Deploy a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA
      - --region=${_DEPLOY_REGION}
      - --platform=${_PLATFORM}
      - --allow-unauthenticated
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
      - --update-env-vars=ATNE_MODEL=mistral

images:
  - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

